title: Hacker Notes
description: My Personal Stack Problems
author: Agus Makmun
github: https://github.com/vjefri
about: Be Curious. Stay Determined.
urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/vjefri
    - text: XML Feed
      url: /feed.xml
url: "jefrivanegas.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown