name: Hacker Notes
description: Be Curious Stay Determined
meta_description: "Programming Blog"

aboutPage: true
markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://jefrivanegas.com'
google_analytics: 'UA-26700148-2'
disqus: true
disqus_shortname: 'jefrivanegas'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Jefri Vanegas'
authorTwitter:  'vjefri'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
